### ISSUE TITLE
建议应跟原生setInterval一致

### ISSUE THREAD

**Issue by GarlandQian** [aweiu/setPromiseInterval#2]
我在项目中应用了这个，感觉很不错，提个不知道算不算issue的问题，我觉得run方法不应该立即执行promise函数，而应跟先等interval毫秒，然后再开始轮询。这样可以和原生事件保持一致。

**Comment by GarlandQian** [comment]
或者也可以做个配置项，需不需要立即执行让使用者自己决定

**Comment by aweiu** [comment]
属于破坏性变更了，暂不考虑。
原因是当时这个特性是刻意为之的：「尽早开始」和「尽早结束」是一组相同的逻辑，作为一个小卖点都这么用了
